### ISSUE TITLE
prapandey031 - The check "msg.sender != tx.origin" in the depositTransaction() of the OptimismPortal.sol can be broken

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-optimism-judging#106]
prapandey031

high

# The check "msg.sender != tx.origin" in the depositTransaction() of the OptimismPortal.sol can be broken

## Vulnerability Detail
The "msg.sender != tx.origin" check in the depositTransaction() of the OptimismPortal.sol ([in line 447](https://github.com/ethereum-optimism/optimism/blob/9b9f78c6613c6ee53b93ca43c71bb74479f4b975/packages/contracts-bedrock/contracts/L1/OptimismPortal.sol#L447)) can be bypassed in 2 ways:

1) If the caller is a wallet that uses ERC4337.
2) If an EOA calls a contract which delegate calls to the depositTransaction() of the OptimismPortal.sol.

## Impact
In both the cases, the "msg.sender != tx.origin" check would be bypassed.

## Tool used

Manual Review

**Comment by GalloDaSballo** [comment]
Recommend Closing as invalid:

I believe a report around SELF-DESTRUCT was also contested due to it being based on future upgrades vs current risks

Another consideration is that tx.origin will be someone even for AA wallets (Bundler's Account is an EOA)
<img width="399" alt="Screenshot 2023-04-11 at 10 50 02" src="https://user-images.githubusercontent.com/13383782/231107417-6ad090c0-6605-4d92-8e51-05d639d61ebd.png">

**Comment by hrishibhat** [comment]
Sponsor comment:
This report is false. If the caller is a wallet that uses ERC4337, it is intended behavior that the address will be aliased. In addition, if the EOA calls a contract that delegatecalls the portal, the check will still not be bypassed and the portal contract itself will not perform the action anyways.
