### ISSUE TITLE
Koolex - L2 block gas limit can be set too high which has critical impact

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-optimism-judging#82]
Koolex

medium

# L2 block gas limit can be set too high which has critical impact

## Summary
L2 block gas limit can be set too high which has impact on op-nodes network and could possibly cause a consensus failure

## Vulnerability Detail
`setGasLimit` method is used to update the L2 gas limit. This can be done only by the owner (i.e. System Config Owner). The method doesn't allow setting the gas limit too low.
```solidity
	require(_gasLimit >= minimumGasLimit(), "SystemConfig: gas limit too low");
```

However, it does allow to set the gas limit too high which should be disallowed. This is very important to ensure that blocks can’t be arbitrarily large. If blocks could be arbitrarily large, then less performant op-nodes would gradually stop being able to keep up with the network. This is even more critical for the sequencers since currently there is only one sequencer.

## Impact
- Less performant op-nodes would gradually stop being able to keep up with the network resulting in a possible consensus failure between the sequencer and verifiers.
- The network is not robust enough and could possibly be slow.

## Code Snippet

https://github.com/sherlock-audit/2023-03-optimism/blob/main/optimism/packages/contracts-bedrock/contracts/L1/SystemConfig.sol#L225

## Tool used

Manual Review

## Recommendation

Add a check for a maximum value of L2 block gas limit to be set. For example, 30M.

**Comment by GalloDaSballo** [comment]
QA because not a vuln, the setting can also easily by the admin

**Comment by hrishibhat** [comment]
Sponsor comment:
This is a design decision for the owner of the system config to be able to parameterize

**Comment by koolexcrypto** [comment]
Escalate for 10 USDC.

I think there is a misunderstanding for the issue. The owner of the system config is able to parameterize the block gas limit which totally makes sense. However, if the owner sets the value too high, the potential for the chain to become quickly bloated is highly likely.  So, an upper bound should be enforced. For example, 60M is safe enough for at least 2 or 3 years. The owner will not need to increase more than that. Anything after that, the contract is still upgradable anyway.

Please note that Optimism **carefully pushed** to increase the block limit from 15M to 30M. Roughly speaking, this was between July 2022 and January 2023. Check [this discussion](https://github.com/ethereum-optimism/optimism/issues/2911#issuecomment-1172482585) for how setting the block limit too high is unsafe.

lastly this issue should be considered as a valid medium since [Issue 89](https://github.com/sherlock-audit/2023-03-optimism-judging/issues/89) is valid medium and caused by the owner of the system config.

Here is a comparison between both issues for a clearer picture.

|   |  [Issue 89](https://github.com/sherlock-audit/2023-03-optimism-judging/issues/89) |  Issue 82 (current issue) |     
|---|---|---|
| **Caused by**  |  The owner of the system config | The owner of the system config  |     
| **Impact irreversibility**  |  not irreversible | not irreversible  |     
|  **Recovery** |  The owner can change the settings again so everything goes back to normal |  The owner can change the settings again so everything goes back to normal |

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC.
> 
> I think there is a misunderstanding for the issue. The owner of the system config is able to parameterize the block gas limit which totally makes sense. However, if the owner sets the value too high, the potential for the chain to become quickly bloated is highly likely.  So, an upper bound should be enforced. For example, 60M is safe enough for at least 2 or 3 years. The owner will not need to increase more than that. Anything after that, the contract is still upgradable anyway.
> 
> Please note that Optimism **carefully pushed** to increase the block limit from 15M to 30M. Roughly speaking, this was between July 2022 and January 2023. Check [this discussion](https://github.com/ethereum-optimism/optimism/issues/2911#issuecomment-1172482585) for how setting the block limit too high is unsafe.
> 
> lastly this issue should be considered as a valid medium since [Issue 89](https://github.com/sherlock-audit/2023-03-optimism-judging/issues/89) is valid medium and caused by the owner of the system config.
> 
> Here is a comparison between both issues for a clearer picture.
> 
> |   |  [Issue 89](https://github.com/sherlock-audit/2023-03-optimism-judging/issues/89) |  Issue 82 (current issue) |     
> |---|---|---|
> | **Caused by**  |  The owner of the system config | The owner of the system config  |     
> | **Impact irreversibility**  |  not irreversible | not irreversible  |     
> |  **Recovery** |  The owner can change the settings again so everything goes back to normal |  The owner can change the settings again so everything goes back to normal |  
> 
> 
> 

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Escalation rejected

Trusted owner input validation is not a valid/high medium in this case.

**Comment by sherlock-admin** [comment]
> Escalation rejected
> 
> Trusted owner input validation is not a valid/high medium in this case. 
> 

This issue's escalations have been rejected!

Watsons who escalated this issue will have their escalation amount deducted from their next payout.
